### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by gaao**
添加必要的"less-loader"依赖

### CODE REVIEW

**Comment by nikku** [comment]
What issue do you fix with this PR?

**Comment by nikku** [comment]
Closed due to missing feedback.

**Comment by gaao** [comment]
> 您通过此 PR 修复了什么问题？

当我使用 pnpm install 安装依赖的时候会提示缺少这个“less-loader”依赖，我加上这个就可以正常运行了

**Comment by barmac** [comment]
We need a bug report with steps to reproduce.

**Pull request closed without merging**
