### PR TITLE
feat: modernize properties-panel example

### PR DESCRIPTION
**Pull request by nikku**
* bump all dependencies
* add start script
* improve styling

---

Should be possible to integration test properties panel releases with this one.

Closes https://github.com/bpmn-io/bpmn-js-examples/issues/125

### CODE REVIEW

**Comment by azeghers** [comment]
Executing `npm run {start|dev|all}` gives me this :
image

**Comment by nikku** [comment]
Works for me:

```
git clone git@github.com:bpmn-io/bpmn-js-examples.git -b bump-properties-panel-example
cd bpmn-js-examples/properties-panel
npm install
npm run dev
```

What is your Node version?

```
node -v
v14.0.0
```

**Comment by azeghers** [comment]
v14.15.1
I tried deleting the node modules for a clean npm install, it doesn't change anything.

**Comment by azeghers** [comment]
Same result with node 14.0.0

**Comment by nikku** [comment]
To double check, https://github.com/bpmn-io/bpmn-js-examples/pull/126#issuecomment-763785992 does not work for you?

**Comment by pinussilvestrus** [comment]
The scroll-tabs arrows look a bit weird on my machine 

image

**Comment by nikku** [comment]
Should be fixed via https://github.com/bpmn-io/bpmn-js-examples/pull/126/commits/4719337997a004e4ea2261ac2d077719e3257eb7?

**Comment by pinussilvestrus** [comment]
> Should be fixed via 4719337?

Jup 👍

**Comment by azeghers** [comment]
Deleting the lockfile worked.
Very minor thing, the carets look fine but they only appear when I click outside of the properties panel after initialization :

https://user-images.githubusercontent.com/42282939/105330566-be5da500-5bd2-11eb-83d6-980ccdf43e29.mp4

**Comment by nikku** [comment]
@azeghers Cannot investigage https://github.com/bpmn-io/bpmn-js-examples/pull/126#issuecomment-764500142 further at the moment. Would you like to give it a try? Otherwise I'd suggest we merge this one. It is a major improvement, after all.

**Comment by azeghers** [comment]
I'm fine with merging it as is.

**Review by azeghers — APPROVED** [review]

**Pull request merged**
