### PR TITLE
feat(angular-example): add angular 7 integration example

### PR DESCRIPTION
**Pull request by dankreiger**
@nikku - re: https://github.com/bpmn-io/bpmn-js-examples/issues/65

- adds a simple angular 7 integration example

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for your pull request, we highly appreciate this contribution!

A few thoughts:

* does it make sense to move the example to a separate repository, i.e. `bpmn-js-example-angular`, maintained under the `bpmn-io` organization? That would allow us to setup CI nicely with it, too.
* could you update the readme with a few pointers for `bpmn-js` how it got integrated and what to look out for? This helps me to evaluate your PR, too (I'm not an angular expert and as such a good first user).

**Comment by dankreiger** [comment]
@nikku 

- it probably makes sense to move this to another repo given the large amount of boilerplate in a new Angular project.

- I will update the README too 👍

**Comment by nikku** [comment]
Could you move your PR to the [bpmn-js-example-angular](https://github.com/bpmn-io/bpmn-js-example-angular) space?

**Comment by nikku** [comment]
> re: CI - should I include a ./circleci/config.yml or travis.yml, or will you add that? I don't know what CI you use.

I'll setup things as appropriate, don't worry about it.

**Comment by dankreiger** [comment]
@nikku I moved it there: https://github.com/bpmn-io/bpmn-js-example-angular/pull/1

**Pull request closed without merging**
