### PR TITLE
feat(properties-panel-list-extension): add basic list example

### LINKED ISSUE #170: Add example for creating properties panel list groups
__What should we do?__

The current [properties panel extension example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension) reflects using the general `Group` for creating custom entries. The `ListGroup` is quite different in consuming (adding `items` instead of `entries`, defining `add` and `remove` handlers).

Also, there is currently no documentation on when to use the `ListEntry` (nested lists) and when to use the `ListGroup` component. We already received [feedback on possible miss-use](https://forum.bpmn.io/t/how-to-use-listentry-in-the-extension-property-panel/7623). Providing a simple example would help here.

* [ ] Add properties panel example using lists

__Why should we do it?__

Be clear on how to use the `ListGroup` component in properties panel extensions.

Context: https://forum.bpmn.io/t/how-to-use-listentry-in-the-extension-property-panel/7623

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #170

This adds an example to show the case of how to support list extensions in the properties panel and the differences between list groups and list entries.

* [x] Showcase ListGroup
* [x] Showcase nested ListEntry

Bildschirmfoto 2022-08-16 um 10 44 55

### CODE REVIEW

**Comment by besley** [comment]
Thanks your example development, in my project we make this component without the camunda modeler support, hope this can be done too.

**Comment by pinussilvestrus** [comment]
Hi @besley thanks for reaching out. This example is not related to the Camunda Modeler but is a basic bpmn.io extension example. 

It can be wrapped into a Camunda Modeler plugin though, but that's not the purpose of this example.

**Comment by nikku** [comment]
I assume what we demo here is already stable / public API, right? If that is the case this is a great addition! :)

**Comment by pinussilvestrus** [comment]
I'd say so, yes 👍  I see people are using it [in the forum](https://forum.bpmn.io/t/how-to-use-listentry-in-the-extension-property-panel/7623) and believe it's sophisticated enough to be used 👍

**Review by nikku — APPROVED** [review]
:+1:

**Comment by stftaf** [comment]
Hi,
Thanks for this example but something seems wrong with :
```
  // Create a group called "parameters".
  const parametersGroup = {
    id: 'parameters',
    label: translate('Magic parameters'),
    component: ListGroup,
    ...parametersProps({ element, injector })
  };
```
The ListGroup constructor fails because there is no 'items' array passed.
If I add `items: [{label: 'Lab', id: 1}]`, it works but that's not my goal.
I can't figure out how to do... If someone could help, it would be great

**Pull request merged**
